name: Build and Deploy Metabase

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl git zip unzip leiningen
        npm install -g yarn
        yarn install

    - name: Build frontend (production)
      run: yarn build

    - name: Package source
      run: |
        cd ..
        zip -r metabase.zip metabase -x "*.git*" "metabase/node_modules/*" "metabase/.github/*"

    - name: Deploy to GCP server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "metabase.zip"
        target: "~/"

    - name: Run Metabase backend (via SSH)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install -y unzip openjdk-21-jdk leiningen
          unzip -o metabase.zip -d metabase
          cd metabase
          nohup clojure -M:run &
